spring:
  application:
    name: sem8
  datasource:
    url: jdbc:h2:mem:userTable
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  thymeleaf:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081